const sampleFolders = {
  "DR-220A": [
    "DR220A_BD.wav",
    "DR220A_CCY.wav",
    "DR220A_CH.wav",
    "DR220A_HCP.wav",
    "DR220A_HT.wav",
    "DR220A_LT.wav",
    "DR220A_MT.wav",
    "DR220A_OH.wav",
    "DR220A_RCY.wav",
    "DR220A_RIM.wav",
    "DR220A_SD.wav",
  ],
  "KPR-77": [
    "KPRCLAPS.WAV",
    "KPRCLHH.WAV",
    "KPRCYMBL.WAV",
    "KPRHITOM.WAV",
    "KPRKICK.WAV",
    "KPRLOTOM.WAV",
    "KPROPHH.WAV",
    "KPRSNARE.WAV",
  ],
  LinnDrum: [
    "cabasa.wav",
    "chhl.wav",
    "chhs.wav",
    "chh.wav",
    "clap.wav",
    "congahh.wav",
    "congah.wav",
    "congalll.wav",
    "congall.wav",
    "congal.wav",
    "conga.wav",
    "cowb.wav",
    "crash.wav",
    "kickme.wav",
    "kick.wav",
    "ohh.wav",
    "ride.wav",
    "sdh.wav",
    "sdl.wav",
    "sd.wav",
    "ssth.wav",
    "sstl.wav",
    "sst.wav",
    "tamb.wav",
    "tomhh.wav",
    "tomh.wav",
    "tomll.wav",
    "toml.wav",
    "tom.wav",
  ],
  "TR-505": [
    "bass-drum-505.wav",
    "closed-hi-hat-505.wav",
    "crash-cymbal-505.wav",
    "hand-clap-505.wav",
    "hi-conga-505.wav",
    "hi-cowbell-505.wav",
    "hi-tom-505.wav",
    "low-conga-505.wav",
    "low-cowbell-505.wav",
    "low-tom-505.wav",
    "mid-tom-505.wav",
    "open-hi-hat-505.wav",
    "ride-cymbal-505.wav",
    "rim-shot-505.wav",
    "snare-drum-505.wav",
    "timbale-505.wav",
  ],
  "TR-606": [
    "606BASS.WAV",
    "606CHAT.WAV",
    "606CYMB.WAV",
    "606HTOM.WAV",
    "606LTOM.WAV",
    "606MHAT.WAV",
    "606OHAT.WAV",
    "606SNAR.WAV",
  ],
  "TR-707": [
    "BassDrum1.wav",
    "BassDrum2.wav",
    "CowBell.wav",
    "Crash.wav",
    "HandClap.wav",
    "HhC.wav",
    "HhO.wav",
    "HiTom.wav",
    "LowTom.wav",
    "MedTom.wav",
    "Ride.wav",
    "RimShot.wav",
    "Snare1.wav",
    "Snare2.wav",
    "Tamb.wav",
  ],
  "TR-727": [
    "727-CABASA.WAV",
    "727-HI-BONGO.WAV",
    "727-HI-TIMBA.WAV",
    "727-HM-CONGA.WAV",
    "727-HO-CONGA.WAV",
    "727-LO-BONGO.WAV",
    "727-LO-CONGA.WAV",
    "727-LO-TIMBA.WAV",
    "727-L.WHISTL.WAV",
    "727-MARACAS.WAV",
    "727-QUIJADA.WAV",
    "727-STARCHIM.WAV",
    "727-S.WHISTL.WAV",
  ],
  "TR-808": [
    "808.mp3",
    "Clap.mp3",
    "Claves.mp3",
    "Conga-High.mp3",
    "Conga-Low.mp3",
    "Conga-Mid.mp3",
    "Cowbell.mp3",
    "Cymbal.mp3",
    "Hihat.mp3",
    "Kick-Basic.mp3",
    "Kick-Long.mp3",
    "Kick-Mid.mp3",
    "Kick-Short.mp3",
    "Maracas.mp3",
    "Open-Hat-Long.mp3",
    "Open-Hat-Short.mp3",
    "Rimshot.mp3",
    "Snare-Bright.mp3",
    "Snare-High.mp3",
    "Snare-Low.mp3",
    "Snare-Mid.mp3",
    "Tom-High.mp3",
    "Tom-Low.mp3",
    "Tom-Mid.mp3",
  ],
};

export const getSampleItems = (
  handleAddSamplerClick: (path: string) => void
) => {
  return Object.entries(sampleFolders).map(([folder, files]) => ({
    label: folder,
    children: files.map((file) => ({
      label: file.replace(/\.(wav|mp3)$/i, ""), // Clean up file extensions for display
      onClick: () => handleAddSamplerClick(`${folder}/${file}`),
    })),
  }));
};
